  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      flutter-version: 'stable' # istersen belirli sürümü yazabilirsin

  - name: Install dependencies
    run: flutter pub get

  - name: Accept Android licenses
    run: yes | sdkmanager --licenses || true
    env:
      ANDROID_HOME: /home/runner/Android/Sdk

  - name: Build debug APK
    run: flutter build apk --debug --no-shrink

  - name: Upload APK artifact
    uses: actions/upload-artifact@v4
    with:
      name: app-debug-apk
      path: build/app/outputs/flutter-apk/app-debug.apk
